many changes, including restructuring of the definition files

diff --git a/scripts/install_longhorn b/scripts/install_longhorn
--- a/scripts/install_longhorn
+++ b/scripts/install_longhorn
@@ -10,13 +10,26 @@
 # You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.
 
 
-inputFile=${1}
+_VERSION="__LABVERSION__"
+[[ "${1}" == "--version" || "${1}" == "-v" ]] && echo "${0##*/} ${_VERSION}" && exit 0
 
-function usage() {
-        echo "Usage:
-$0 <configuration file>"
+# load lab_creation defaults
+if [[ -f /etc/lab_creation.defaults ]]
+then
+        . /etc/lab_creation.defaults
+elif [[ -f lab_creation.defaults ]]
+then
+        . lab_creation.defaults
+else
+        echo "ERROR: Configuration file lab_creation.defaults not found in local path or /etc"
+        exit 1
+fi
 
-}
+# Load primary functions
+. ${_primary_funtions} || exit 1
+
+# load Kubernetes functions
+. ${_lib_path}/k8s_functions.bash
 
 # Setup SUSE Longhorn helm repository
 function setup_lh_repo() {
@@ -28,54 +41,15 @@ function setup_lh_repo() {
 
  # Setup SUSE Longhorn
 function setup_lh() {
+                $ssh_command "zypper install -y open-iscsi cryptsetup; systemctl enable --now iscsid.service ; modprobe iscsi_tcp"
                 $ssh_command "kubectl create namespace longhorn-system"
-                $ssh_command "helm upgrade -i longhorn longhorn/longhorn --namespace longhorn-system --set ingress.enabled=true --set ingress.host=${lh_shorthn:-longhorn}.${clu_name}.${mydomain}"
+                $ssh_command "helm upgrade -i longhorn longhorn/longhorn --namespace longhorn-system --set ingress.enabled=true --set ingress.host=${lh_shorthn:-longhorn}.${clu_name}.${mydomain}  --set persistence.migratable=true --set longhornUI.replicas=1"
                 echo "Longhorn should be available in a few minutes in: ${lh_shorthn:-longhorn}.${clu_name}.${mydomain}"
 }
  
 
-if [[ ! ${inputFile} ]]
-then
-        echo "missing configuration file parameter"
-        usage
-        exit 1
-fi
-
-if [[ ! -f ${inputFile} ]]
-then
-        echo "configuration file \"${inputFile}\" not found or name incorrect"
-        usage
-	exit 1
-elif ! jq <"${inputFile}" >/dev/null
-then
-   echo "Cluster definition not in validated JSON format"
-   exit 1
-fi
-
-
-# load lab_creation config
-if [[ -f /etc/lab_creation.cfg ]]
-then
-        . /etc/lab_creation.cfg
-elif [[ -f lab_creation.cfg ]]
-then
-        . lab_creation.cfg
-else
-        echo "ERROR: Configuration file lab_creation.cfg not found in local path or /etc"
-        exit 1
-fi
-
-if [[ ! -f ${_lib_path} ]]
-then
-        echo "ERROR: Library \"${_lib_path}\" not found"
-        exit 1
-else
-        # load library
-        . ${_lib_path}
-fi
-
 # load cluster vars
-load_cluster_vars
+load_kclu_vars
 
 # load rancher variables
 load_rancher_vars
diff --git a/scripts/install_rancher b/scripts/install_rancher
--- a/scripts/install_rancher
+++ b/scripts/install_rancher
@@ -9,19 +9,33 @@
 #
 # You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.
 
-inputFile=${1}
+_VERSION="__LABVERSION__"
+[[ "${1}" == "--version" || "${1}" == "-v" ]] && echo "${0##*/} ${_VERSION}" && exit 0
 
-function usage() {
-        echo "Usage:
-$0 <configuration file>"
+# load lab_creation defaults
+if [[ -f /etc/lab_creation.defaults ]]
+then
+        . /etc/lab_creation.defaults
+elif [[ -f lab_creation.defaults ]]
+then
+        . lab_creation.defaults
+else
+        echo "ERROR: Configuration file lab_creation.defaults not found in local path or /etc"
+        exit 1
+fi
 
-}
+# Load primary functions
+. ${_primary_funtions} || exit 1
+
+# load Kubernetes functions
+. ${_lib_path}/k8s_functions.bash || exit 1
 
 # Setup SUSE Rancher helm respoitory
 function setup_rancher_repo() {
         _repo_name="${rancher_rel:-rancher-stable/rancher}"
         _repo_url="${rancher_repo_url:-https://releases.rancher.com/server-charts/stable}"
         helm_repo_add
+
         _repo_name="${rancher_cert_repo_name:-jetstack}"
         _repo_url="${rancher_cert_repo_url:-https://charts.jetstack.io}"
         helm_repo_add
@@ -31,99 +45,113 @@ function setup_rancher_repo() {
 # Setup cert-manager
 function setup_cert-manager() {
         # https://cert-manager.io/docs/installation/helm/
-        echo "# Setup Cert-manager"
-        $ssh_command "helm upgrade -i cert-manager jetstack/cert-manager ${cert_manager_ver} --namespace cert-manager --create-namespace --set installCRDs=true"
+        _msg="# Setup Cert-manager" show_nicer_messages
+
+        local _install_cert_manager="helm upgrade -i cert-manager jetstack/cert-manager ${cert_manager_ver} --namespace cert-manager --create-namespace --set installCRDs=true"
+        $ssh_command "${_install_cert_manager}" || _msg="$ssh_command \"${_install_cert_manager}\"" fail_with_error
+        $ssh_command "kubectl wait pods -n cert-manager -l app.kubernetes.io/instance=cert-manager --for condition=Ready --timeout=120s 2>/dev/null"
+        $ssh_command "kubectl apply -f -" <<EOF
+---
+apiVersion: cert-manager.io/v1
+kind: ClusterIssuer
+metadata:
+  name: letsencrypt-ci
+spec:
+  acme:
+    server: https://acme-staging-v02.api.letsencrypt.org/directory
+    email: none@someunknowndomain.com
+    privateKeySecretRef:
+      name: letsencrypt-staging
+    solvers:
+      - http01:
+          ingress:
+            class: ${ingressClassname:-traefik}
+...
+---
+apiVersion: cert-manager.io/v1
+kind: ClusterIssuer
+metadata:
+  name: letsencrypt-prod
+spec:
+  acme:
+    server: https://acme-v02.api.letsencrypt.org/directory
+    email: none@someunknowndomain.com
+    privateKeySecretRef:
+      name: letsencrypt-prod
+    solvers:
+      - http01:
+          ingress:
+            class: ${ingressClassname:-traefik}
+EOF
+
+
+
 }
 
  
 # Setup SUSE Rancher
 function setup_rancher() {
-        echo "# Setup Rancher ${rancher_repo:-jjjj}"
-        $ssh_command "helm upgrade -i ${rancher_helm_rel:-rancher} ${rancher_helm_chart} --create-namespace --namespace cattle-system --set hostname="${rancher_shorthn}.${clu_name}.${mydomain}" --set bootstrapPassword=\"${rancher_initial_pwd}\""
-        echo "# Get initial password: "
-        $ssh_command "kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}{{ \"\n\" }}'"
+        msg="# Setup Rancher ${rancher_helm_rel:-rancher} in cluster \"${clu_name}\"" show_nicer_messages
+#        $ssh_command "helm upgrade -i ${rancher_helm_rel:-rancher} ${rancher_helm_chart} --create-namespace --namespace cattle-system --set hostname=\"${rancher_shorthn}.${clu_name}.${mydomain}\" ${rancher_version} --set bootstrapPassword=\"${rancher_initial_pwd}\" --set replicas=${rancher_replicas:-2} --set ingress.extraAnnotations.'cert-manager\.io/cluster-issuer'=letsencrypt-prod --set ingress.tls.source=secret --set ingress.tls.secretName=tls-rancher --set agentTLSMode=\"system-store\"" || exit 1
+
+        $ssh_command "helm upgrade -i ${rancher_helm_rel:-rancher} ${rancher_helm_chart} --create-namespace --namespace cattle-system --set hostname=\"${rancher_shorthn}.${clu_name}.${mydomain}\" ${rancher_version} --set bootstrapPassword=\"${rancher_initial_pwd}\" --set replicas=${rancher_replicas:-2} " || exit 1
 
         # verify it's up and running
         # kubectl -n cattle-system rollout status deploy/rancher
         # kubectl -n cattle-system get deploy rancher
 
-        echo "## Add Rancher DNS"
+        _msg="## Add Rancher DNS" show_nicer_messages
         _dns_entry="${rancher_shorthn:-ERROR_ranchershort}.${clu_name}"
         add_service_dns
-        echo "Service will be ready at ${insecure_app_name:-webphotobook}.${clu_name}.${mydomain}"
 
-        for _dns in $(jq -r '.nodes | to_entries[].key' < ${inputFile} |xargs)
-        do
-                        add_dns_to_named_rr
+
+
+        local clu_type_u="${clu_type^^}" 
+        local matching_nodes
+        matching_nodes=$(jq -r --arg ctype "INSTALL_${clu_type_u}_TYPE" --arg cname "${clu_name}" '
+            .nodes | to_entries[] | select(.value[$ctype] == "server" and .value.kcluster == $cname) | .key
+        ' < "${inputFile}")
+
+        for _dns in $matching_nodes; do
+            add_dns_to_named_rr
         done
+
         systemctl restart named
-        echo "Wait 5 minutes for the installation to finish"
-        sleep 300
+
+        _msg="Wait for rancher to be ready" show_nicer_messages
+        $ssh_command 'kubectl wait pods -n cattle-system -l app=rancher --for condition=Ready --timeout=300s'
+#        $ssh_command 'while ! kubectl get secret rancher-tls --namespace cattle-system 2>/dev/null; do sleep 1; done; sleep 10'
+        sleep 60
+
+        initial_rancher_pwd=$($ssh_command "kubectl get secret --namespace cattle-system bootstrap-secret -o jsonpath='{.data.bootstrapPassword}' | base64 -d") || { _msg="Failed to retrieve bootstrap secret" fail_with_error; }
+
+        _msg="# Initial password: ${initial_rancher_pwd}" show_nicer_messages
+#        initial_rancher_pwd=`$ssh_command "kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}{{ \"\n\" }}'" || exit 1`
 
 }
 
 
 
-if [[ ! ${inputFile} ]]
-then
-        echo "missing configuration file parameter"
-        usage
-        exit 1
-fi
-
-if [[ ! -f ${inputFile} ]]
-then
-        echo "configuration file \"${inputFile}\" not found or name incorrect"
-        usage
-	exit 1
-elif ! jq <"${inputFile}" >/dev/null
-then
-   echo "Cluster definition not in validated JSON format"
-   exit 1
-fi
-
-# load lab_creation config
-if [[ -f /etc/lab_creation.cfg ]]
-then
-        . /etc/lab_creation.cfg
-elif [[ -f lab_creation.cfg ]]
-then
-        . lab_creation.cfg
-else
-        echo "ERROR: Configuration file lab_creation.cfg not found in local path or /etc"
-        exit 1
-fi
-
-if [[ ! -f ${_lib_path} ]]
-then
-        echo "ERROR: Library \"${_lib_path}\" not found"
-        exit 1
-else
-        # load library
-        . ${_lib_path}
-fi
-
-
 # load cluster vars
-load_cluster_vars
+load_kclu_vars
 
 # load rancher variables
 load_rancher_vars
 
 
 # find a server node or API url
-for _vm_name in $(jq -r '.nodes | to_entries[].key' < ${inputFile} |xargs)
-do
-	load_vm_vars
-	ssh_command="ssh  -o StrictHostKeyChecking=accept-new -q  root@${_vm_name}"
-	if [[ "${INSTALL_RKE2_TYPE}" == "server" || "${INSTALL_RKE2_TYPE}" == "" ]]
-	then
-		echo "# Using node: $_vm_name"
-		setup_helm
-		setup_rancher_repo
-		setup_cert-manager
-		setup_rancher
-		exit 1
-	fi
-done
+load_vm_vars
+
+ssh_command="ssh  -o StrictHostKeyChecking=accept-new -q  root@${_vm_name}"
+
+if [[ "${INSTALL_RKE2_TYPE}" == "server" || "${INSTALL_RKE2_TYPE}" == "" ]]
+then
+	_msg="Using node: \e[1;91m\"${_vm_name}\"\e[0m" show_nicer_messages
+	setup_helm
+	_msg="Setup_rancher_repo" show_nicer_messages
+	setup_rancher_repo
+	setup_cert-manager
+	setup_rancher
+	exit 1
+fi
 
diff --git a/scripts/install_suma b/scripts/install_suma
--- a/scripts/install_suma
+++ b/scripts/install_suma
@@ -10,13 +10,24 @@
 # You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.
 
 
-inputFile=${1}
+_VERSION="__LABVERSION__"
+[[ "${1}" == "--version" || "${1}" == "-v" ]] && echo "${0##*/} ${_VERSION}" && exit 0
 
-function usage() {
-        echo "Usage:
-$0 <configuration file>"
+# load lab_creation defaults
+if [[ -f /etc/lab_creation.defaults ]]
+then
+        . /etc/lab_creation.defaults
+elif [[ -f lab_creation.defaults ]]
+then
+        . lab_creation.defaults
+else
+        echo "ERROR: Configuration file lab_creation.defaults not found in local path or /etc"
+        exit 1
+fi
 
-}
+# Load primary functions
+. ${_primary_funtions} || exit 1
+
 
 
 # Load SUMA related variables.
@@ -29,19 +40,76 @@ function load_suma_vars() {
 
 # Setup suma
 function setup_suma() {
-                $ssh_command "transactional-update register -p ${suma_channel:-SUSE-Manager-Server/5.0/x86_64} -r ${suma_key:-aaaaaa} ; reboot"
-                sleep 60
-                $ssh_command "transactional-update pkg install -y mgradm-bash-completion mgrctl-bash-completion mgradm-zsh-completion mgrctl-zsh-completion; reboot"
-                sleep 60
+                _msg="- Registering system to SUMA channel" show_nicer_messages
+                $ssh_command "transactional-update --quiet register -p ${suma_channel:-SUSE-Manager-Server/5.0/x86_64} -r ${suma_key:-aaaaaa} ; reboot"
+                sleep 5
+                check_ssh_conn
+                _msg="- install utility packages" show_nicer_messages
+
+                $ssh_command "transactional-update --quiet pkg install -y mgradm-bash-completion mgrctl-bash-completion mgradm-zsh-completion mgrctl-zsh-completion; reboot"
+                sleep 5
+                check_ssh_conn
+                if [[ "${extra_dsk}" != "" ]]
+                then
+                  for _dsk in ${extra_dsk}
+                  do
+                    _msg="- Adding extra disk ${_dsk}" show_nicer_messages
+                    #if [[ "${_dsk}" =~ "UUID" ]]
+                    #then
+                      $ssh_command "echo \"mirror /srv/mirror 9p trans=virtio,version=9p2000.L,nofail,_netdev,x-mount.mkdir 0 0\" >> /etc/fstab ;  mkdir /srv/mirror"
+                    #  _dsk="${_dsk//,*}"
+                    #  _dsk=`$ssh_command "lsblk -o UUID,PATH | grep ${_dsk//UUID=} | cut -d' ' -f2"`
+                    #  $ssh_command "mgr-storage-server ${_dsk}"
+                    #fi
+                    $ssh_command "echo \"${_dsk//,*} ${_dsk//*,} xfs defaults,nofail 1 2\" >>/etc/fstab"
+                  done
+                  $ssh_command "reboot"
+                  sleep 5
+                  check_ssh_conn
+
+                else
+                   echo "NO EXTRA_DSK "
+                fi
+                _msg="- Installing SUMA" show_nicer_messages
+
                 $ssh_command "podman login --username  ${suma_reg_username:-admin@mydemo.lab} --password ${suma_reg_pwd:-aaaaaaaa} registry.suse.com"
-                $ssh_command "mgradm install --admin-password ${suma_adm_pwd:-admin123} --ssl-password ${suma_ssl_pwd:-admin123}  --admin-email ${suma_adm_email:-admin@mydemo.lab} --scc-user ${suma_scc_user:-XYZ} --scc-password ${suma_scc_pwd:-admin123}  podman"
+                
+                template_file=${_templ_addons_loc}/suma/mgradm.yaml.tmpl
+                process_templates | $ssh_command "cat > /var/tmp/mgradm.yaml"
+                
+#                $ssh_command "mgradm install --admin-password ${suma_adm_pwd:-admin123} --ssl-password ${suma_ssl_pwd:-admin123}  --admin-email ${suma_adm_email:-admin@mydemo.lab} --scc-user ${suma_scc_user:-XYZ} --scc-password ${suma_scc_pwd:-admin123} --mirrorPath ${suma_mirrorPath:-/srv/mirror} --organization ${suma_def_org:-mydemo}  podman"
+
+                $ssh_command "mgradm -c /var/tmp/mgradm.yaml install podman "
+
                 sleep 120
+
                 $ssh_command "reboot"
-                sleep 60
-                echo "SUMA should be available in a few minutes, visit https://${_vm_name}/"
+
+                sleep 5
+                check_ssh_conn
+
+                _msg="- Sync admin user password" show_nicer_messages
+
+                $ssh_command "mgrctl exec -- \"echo -e 'mgrsync.user = admin\nmgrsync.password = ${suma_adm_pwd:-admin123}' >~/.mgr-sync\""
+
+                _msg="SUMA should be available in a few minutes, visit https://${_vm_name}/" show_nicer_messages
                 if [[ "${suma_channels}" != "" ]]
                 then
-                  echo "We will start the process of synching the selected channels, this may take hours"
+                  _count=0
+                  _msg="`date` - Let's wait for the channel list to sync'"  show_nicer_messages
+                  while true
+                  do
+                    sleep 5
+                    ((_count+=1))
+                    printf "Retry $_count\r"
+                    $ssh_command  "mgrctl exec -- mgr-sync list channels 2>/dev/null " | grep -iv 'No channels found.'
+                    if test $? -eq 0
+                    then
+                      break
+                    fi
+                  done
+                  _msg="`date` - We will start the process of synching the selected channels, this may take hours" show_nicer_messages
+                  echo "list: $suma_channels "
                   # wait 5 minutes to let SUMA start
                   sleep 300
                   $ssh_command "mgrctl exec -- mgr-sync add channels ${suma_channels}"
@@ -49,55 +117,31 @@ function setup_suma() {
 }
 
 
-if [[ ! ${inputFile} ]]
-then
-        echo "missing configuration file parameter"
-        usage
-        exit 1
-fi
-
-if [[ ! -f ${inputFile} ]]
-then
-        echo "configuration file \"${inputFile}\" not found or name incorrect"
-        usage
-	exit 1
-elif ! jq <"${inputFile}" >/dev/null
-then
-   echo "Cluster definition not in validated JSON format"
-   exit 1
-fi
-
-# load lab_creation config
-if [[ -f /etc/lab_creation.cfg ]]
-then
-        . /etc/lab_creation.cfg
-elif [[ -f lab_creation.cfg ]]
-then
-        . lab_creation.cfg
-else
-        echo "ERROR: Configuration file lab_creation.cfg not found in local path or /etc"
-        exit 1
-fi
-
-if [[ ! -f ${_lib_path} ]]
-then
-        echo "ERROR: Library \"${_lib_path}\" not found"
-        exit 1
-else
-        # load library
-        . ${_lib_path}
-fi
-
 
 # load insecure_app variables
 load_suma_vars
 
 
-
-load_vm_vars
-ssh_command="ssh  -o StrictHostKeyChecking=accept-new -q  root@${_vm_name}"
-echo "# Using node: $_vm_name"
-setup_suma
-
+if [[ "${_vm_name}" == "" ]]
+then
+  for _vm_name in $(jq -r '.nodes | to_entries[].key' < ${inputFile} |xargs )
+  do
+    for _addon in $(jq -r ".nodes.\"${_vm_name}\".addons[]" < ${inputFile} 2>/dev/null )
+    do
+      if [[ "${_addon}" == "suma" ]]
+      then
+        load_vm_vars
+        ssh_command="ssh  -o StrictHostKeyChecking=accept-new  root@${_vm_name}"
+        _msg="- Using node: $_vm_name" show_nicer_messages
+        setup_suma
+      fi
+    done
+  done
+else
+  load_vm_vars
+  ssh_command="ssh  -o StrictHostKeyChecking=accept-new root@${_vm_name}"
+  _msg="- Using node: $_vm_name" show_nicer_messages
+  setup_suma
+fi
 
 
